<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageId>PhoneNumberInput.Blazor</PackageId>
		<Version>1.0.0</Version>
		<FileVersion>1.0.0</FileVersion>
		<Authors>Perić Željko, periczeljkosmederevo@yahoo.com</Authors>
		<Company>periczeljkosmederevo@yahoo.com</Company>
		<Description>Reusable Blazor component for phone number input with continent/country filtering.</Description>
		<PackageLicenseExpression>CC0-1.0</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Copyright>Copyright © 2026</Copyright>
		<Title>Custom Blazor Phone Number Input Component</Title>
		<PackageProjectUrl>https://github.com/periczeljkosmederevo/Blazor_Custom_Input_Phone_Number_Component</PackageProjectUrl>
		<PackageIcon>TM 500.png</PackageIcon>

		<RepositoryUrl>https://github.com/periczeljkosmederevo/Blazor_Custom_Input_Phone_Number_Component</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<PackageProjectUrl>https://github.com/periczeljkosmederevo/Blazor_Custom_Input_Phone_Number_Component</PackageProjectUrl>

		<PackageReleaseNotes>Initial release of the Blazor Phone Number Input component with continent and country filtering features.</PackageReleaseNotes>
	</PropertyGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.10" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
		<None Include="..\TM 500.png">
		  <Pack>True</Pack>
		  <PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
</Project>