<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageId>PhoneNumberInput.Blazor</PackageId>
		<Version>10.0.11</Version>
		<FileVersion>10.0.11</FileVersion>
		<Authors>Perić Željko, periczeljkosmederevo@yahoo.com</Authors>
		<Company>periczeljkosmederevo@yahoo.com</Company>
		<Description>Reusable Blazor component for phone number input with continent/country filtering.</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Copyright>Copyright © 2026</Copyright>
		<Title>Custom Blazor Phone Number Input Component</Title>
		<PackageProjectUrl>https://github.com/periczeljkosmederevo/Blazor_Custom_Input_Phone_Number_Component</PackageProjectUrl>
		<PackageIcon>TM 500.png</PackageIcon>
		<RepositoryUrl>https://github.com/periczeljkosmederevo/Blazor_Custom_Input_Phone_Number_Component</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageProjectUrl>https://github.com/periczeljkosmederevo/Blazor_Custom_Input_Phone_Number_Component</PackageProjectUrl>
		<PackageReleaseNotes>- Added support for local SVG country flags in the dropdown and selection buttons (supports 1x1 and 4x3 flag sets).
- Added 'ShowFlags' parameter to easily toggle flag visibility on or off.</PackageReleaseNotes>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
	</PropertyGroup>
	<ItemGroup>
	  <None Include="..\LICENSE.txt">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Include="..\README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Include="..\TM 500.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.11" />
	</ItemGroup>
</Project>